theme: jekyll-theme-minimal
title: Alex Ganose
description: Welcome to the research website of Alex Ganose.
  I'm currently a PhD candidate in Computational Chemistry at 
  University College London.
