theme: jekyll-theme-minimal
title: Alex Ganose
description: Welcome to the research website of Alex Ganose.
  I'm currently a final year EngD candidate in Computational
  Chemistry at University College London.
github_username: utf
twitter_username: alexganose
