theme: jekyll-theme-minimal
title: Alex Ganose
description: Welcome to the research website of Alex Ganose.
  I'm a Postdoc working in theoretical materials science and
  machine learning at LBNL.
github_username: utf
twitter_username: alexganose
